### ISSUE TITLE
The hash function

### ISSUE THREAD

**Issue by wboeke** [dzshy/reinforth#1]
Hello,

Is there any reason to use such a complicated hash function, containing a big crc array?
I tried a very simple standard hash function:
  int ret=0;
  while (size--) ret += 31 * buf[size];
  return ret;
No dynamic rehashing, fixed capacity = 256. No problems, and a lot less code.

I like this forth program: it's standard forth, and very well hackable. I collected all source code in one file, about 2000 lines, compiling in 0.5 sec. Thanks a lot!

Wouter Boeke

**Comment by dzshy** [comment]
Yes, I also find out that the hash table is a little too complicated. Actually, I'm going to use a linked list instead, just like a standard Forth.

BTW, this is not a standard Forth. I have modified some syntax and behavior according to my personal taste. For example, the string literal is `"hello world"`, but not `" hello world"`.

**Comment by dzshy** [comment]
Done with https://github.com/dzshy/reinforth/commit/7822b5871ad6e38d6de54bdf72292c64312eabff
