### ISSUE TITLE
Implement DOES> ?

### ISSUE THREAD

**Issue by wboeke** [dzshy/reinforth#2]
Hello, it's me again.
In reinforth there is one very useful operator missing: DOES>. Is it possible for you to add it?

Kind regards,
Wouter Boeke

**Comment by dzshy** [comment]
Implementing `DOES>` is not trivial but I think it's quite simple. I will try it when I have time.

Also, PR is welcome.

**Comment by dzshy** [comment]
Done with https://github.com/dzshy/reinforth/commit/04e758f5569e8b41b96f18e7f55eabee2ec94518
